### ISSUE TITLE
Add scrollspy

### ISSUE THREAD

**Issue by barriehadfield** [hyperstack-org/website#21]
When scrolling down a page, as a section heading comes into view the selected class should be applied. Sahe for when a page is opened, the correct heading should be highlighted.

**Comment by sfcgeorge** [comment]
I believe this can be done with pure CSS now which would be better for performance and simplicity :)

**Comment by barriehadfield** [comment]
Just seen Simon's comment - just as I come to close the issue having completed it :-) Oh well, not pure CSS, but perhaps that can be done sometime in the future. For now its using a Store, but has been quite tricky to implement as the events that drive it fire whenever the page is rendered.
