### ISSUE TITLE
Docs link stuck on Loading Pages

### ISSUE THREAD

**Issue by wr0ngway** [hyperstack-org/website#31]
This is on https://hyperstack.org/edge/docs
Can browse the docs via github instead, but thought you should know about the main site being broken

**Comment by barriehadfield** [comment]
@wr0ngway thanks for that! Looks like one of the tutorial MD pages has something in it the HTML converter is not dealing with, but I was not catching the JS exception, so the loading process was not seeing the page not being loaded and hence the infinite spinner. I am changed it to catch the exception and just not load the page.
